a , b=1 , 1
arestdyfughjlk,esdtfyguio=12345678,12345678
print(arestdyfughjlk,esdtfyguio,a,b)
print(a,b,a,b,a,b,end="북")
print(a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b)
print(a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,a,b,end="..ㅣ.ㅡ")
q , w="김정은vs조바이든+","김정은vs조바이든+"
print(q,w,q,w,q,w,q,w,q,w,q,w,end=" 핵   =핵전쟁")
redpig,biackpig=("킹카"),("킹카")
redpig,biackpig=("킹카"),("킹카")
print(redpig,biackpig)
print(a,b,sep="x")
print(a,a,a,a,a,a,a,a,a,a,b,b,sep="x",end="=김정은뱃살")
print("ixeztryoctupvyipfct8d7ors6iea5uzixrtycotxri6sezrxyctxorsi6xctxodrsixtcyxrdsi6tdrsdtfdrstfytdrseardftgftdrsea4wesdrftghjkhgfdresdrftyguhijkljhgfdsfgyuhijkolplkjhgfdguhijokjihugfdhjkljhgfhjklhgfdhjkljhgfdgjlfdguyipugjfhgh")
print("HGEHJLRThrtjhrwhjhufrhu;irgtejklgrhlkjskglearfwhgrs.k;uhggggggggggghewrtfkygliuhogiyfutkdyrjtfugiyfutdyrjtfkugiltyrkdsneasdyiguoyftdsnhgiuoh/gufydhmxgjkliugkfxmcg,jvklgfchvbjnlhgcmxgjk.l/hgkfmdyuoi/ygf,jtduygihlkjgcnvj,hk.hlftdjyuipghkfjuiopjhfgdmtuy798oiudtjer6iluyhjk.gftkru7iluyhjgkftur67iuyolhkjgmfjmtruyiljkbnmfghtry6587iuyhjk,bgfyru65879piouytr67587908puoiljkhg,ykut7698uojkhjgkut7697809[iopklnbjghkt76=90-opkljhgfyut6789809pio;kljm.n,bvmgjfutr67587980ipok;lm.,n,bmvgcftr67890-0iop[klm,.n bvgfmktr6879809ioklmn∫vgftr67809-io[klmnbv,gfktrui6o78p909[i'o[kljh.g,jfmktrj5i6789iokljbnvcdftr768uoijkhbvgcfmdrjet6t7y;iouhjgvgcfxhmdret6t7yu]]]]]")
print(1,2,3)
print(112345623)
print(1,2,3,sep="x")
print(1,2,3,sep="x",end="=6")
print()
print(2,5,sep="x",end="=10")
print()
print("printprintprintprintprintprintprintprintprintprintprintprintprintprint")
print("러북다이브    -릴도지-")
print("-김정일-  기강찬 군부대 그건 '러'도 마찬가지")
print("-김정일-  이거면 충분해 돕고돕는 이런놀이")
print("-김정은-  참을 수 없는 미사일과 허기짐")
print(" -푸틴-  묘한 '러'와 나 두 동무는 알겠디")